name: test_svg
description: TestSvg

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  flutter_gen_runner: 5.1.0+1

flutter_gen:
  output: lib/resource/gen/

  integrations:
    flutter_svg: true
    style: came-case

flutter:

  uses-material-design: true

  #https://www.svgrepo.com/collection/dazzle-line-icons/
  assets:
    - assets/images/
    - assets/walk/